version: '3.8'
services:
  lannister_db:
    image: postgres:14
    container_name: lannister_db
    hostname: localhost
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d