version: '3.8'
services:
  slack_app:
    build: ./Lannister/slack_app
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    ports:
      - "3000:3000"
    command: python app.py
